services:

  # Database needed to store the test data
  icat_mariadb:
    restart: always
    # note: the latest version does not support the SQL connector needed by icat
    image: mariadb:10.10
    container_name: icat_mariadb_container
    # note: in the case that something else is already running on 3306 locally,
    # this can be changed or removed without affecting the tests which connect
    # directly to the icat_mariadb service without using port forwarding
    # ports:
    #   - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pw
      MARIADB_DATABASE: icatdb
      MARIADB_USER: icatdbuser
      MARIADB_PASSWORD: icatdbuserpw
    # the health check will tell us when data is in the DB
    healthcheck:
      test: "/usr/bin/mysql --database=$$MARIADB_DATABASE --user=$$MARIADB_USER --password=$$MARIADB_PASSWORD --execute \"SHOW TABLES;\""
      interval: 10s
      timeout: 2s
      retries: 10
    networks:
      - datastore_network
    profiles: [dependencies, tests, full]

  # The ICAT server, available at https://localhost:18181/icat/version
  icat_payara:
    restart: always
    image: harbor.stfc.ac.uk/icat/icat_5:latest
    container_name: icat_payara_container
    depends_on:
      icat_mariadb:
        condition: service_healthy
    ports:
      - "14747:4848" # payara port
      - "18181:8181" # https port
      - "18080:8080" # http port
    volumes:
      - type: bind
        source: tests/post-boot-commands.asadmin
        target: /config/post-boot-commands.asadmin
    environment:
      - POSTBOOT_COMMANDS=/config/post-boot-commands.asadmin
    healthcheck:
      test: curl --fail http://localhost:8080/icat/version || exit 1
      interval: 10s
      timeout: 2s
      retries: 10
    networks:
      - datastore_network
    profiles: [dependencies, tests, full]

  # The Auth service needed by ICAT, available at https://localhost:28181/authn.simple/version/
  auth_payara:
    restart: unless-stopped
    image: harbor.stfc.ac.uk/icat/icat_auth:latest
    container_name: auth_payara_container
    ports:
      - "24747:4848"
      - "28181:8181"
    networks:
      - datastore_network
    profiles: [dependencies, tests, full]

  # The minio instance that simulates s3 buckets for download functionality
  # UI available at http://localhost:9000
  minio:
    image: quay.io/minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    healthcheck:
      test: /usr/bin/mc ls data
      interval: 10s
      timeout: 2s
      retries: 10
    networks:
      - datastore_network
    profiles: [minio]

  # Script that inits minio with a bucket and an object
  mc:
    image: minio/mc
    container_name: mc
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      until /usr/bin/mc alias set data http://minio:9000 minioadmin minioadmin; do
        sleep 1
      done;
      /usr/bin/mc mb data/cache-bucket;
      /usr/bin/echo "test" | mc pipe data/cache-bucket/test;
      /usr/bin/echo "test0" | mc pipe data/cache-bucket/test0;
      /usr/bin/echo "test2" | mc pipe data/cache-bucket/test2;
      /usr/bin/echo "test3" | mc pipe data/cache-bucket/test3;
      exit 0;
      "
    networks:
      - datastore_network
    profiles: [minio]

  format:
    container_name: datastore_api_format
    build:
      context: .
      target: dev
    command: black datastore_api tests
    profiles: [format, checks]

  lint:
    container_name: datastore_api_lint
    build:
      context: .
      target: dev
    command: flake8 datastore_api tests
    profiles: [lint, checks]

  safety:
    container_name: datastore_api_safety
    build:
      context: .
      target: dev
    command: safety check --full-report --ignore=75180
    profiles: [safety, checks]

  tests:
    container_name: datastore_api_tests
    build:
      context: .
      target: dev
    depends_on:
      icat_payara:
        condition: service_healthy
      auth_payara:
        condition: service_started
    volumes:
      - type: bind
        source: ./coverage.xml
        target: /app/coverage.xml
      - type: bind
        source: ./hostkey.pem
        target: /app/hostkey.pem
      - type: bind
        source: ./hostcert.pem
        target: /app/hostcert.pem
    command: pytest tests --cov --cov-report=term-missing --cov-report=xml
    networks:
      - datastore_network
    profiles: [tests]

  datastore-api:
    container_name: datastore_api
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      icat_payara:
        condition: service_healthy
    networks:
      - datastore_network
    profiles: [full]

  testdata:
    image: harbor.stfc.ac.uk/icat/icat_testdata:latest
    container_name: testdata_container
    depends_on:
      icat_payara:
        condition: service_healthy
    networks:
      - datastore_network
    profiles: [full]

volumes:
  minio_data:

networks:
  datastore_network:
